# Generated by Django 5.0.6 on 2024-06-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referralcode',
            old_name='expires_at',
            new_name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='referralcode',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='referralcode',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
